/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * One completed detection, kept in Rust so every encoder sees the same
 * deterministic report.
 */
export declare class NativeCloneReport {
  get pairCount(): number
  get familyCount(): number
  /** Returns the stable `clone-report/v1` JSON document. */
  json(): string
  /** Returns a SARIF 2.1.0 run for code-scanning consumers. */
  sarif(): string
  /** Returns the `BigCloneEval` pair export. */
  bigCloneEval(): string
}

/** Detects clones over fragments the caller supplies; no filesystem access. */
export declare function detectFragments(fragmentsJson: string, optionsJson?: string | undefined | null): NativeCloneReport

/** Scans a repository once and detects clone families off the event loop. */
export declare function detectRepository(root: string, optionsJson?: string | undefined | null): Promise<unknown>

/** Scans a repository once and detects clone families on the calling thread. */
export declare function detectRepositorySync(root: string, optionsJson?: string | undefined | null): NativeCloneReport

/** The JSON Schema document describing `json()`. */
export declare function jsonSchema(): string

/** The identifier of the report schema `json()` emits. */
export declare function jsonSchemaId(): string
